### ISSUE TITLE
Can component be imported to slides? 

### ISSUE THREAD

**Issue by xianx** [fabe/gatsby-starter-deck#15]
Do importing component and declare on slide .md file works?

**Comment by fabe** [comment]
This is currently not possible, although you could install and set up [`gatsby-remark-component`](https://www.gatsbyjs.org/packages/gatsby-remark-component/) or [`gatsby-remark-custom-blocks`](https://www.gatsbyjs.org/packages/gatsby-remark-custom-blocks/) without too much trouble.

I have been thinking about supporting [`gatsby-mdx`](https://github.com/ChristopherBiscardi/gatsby-mdx) out of the box, but that could mean some breaking changes. I'll keep this issue open until I can look into it more 🙂

**Comment by fabe** [comment]
I'm archiving this repository in favor of https://github.com/jxnblk/mdx-deck/tree/master/packages/gatsby-theme ✌️
