### ISSUE TITLE
Large images are overflowing or cropping in height.

### ISSUE THREAD

**Issue by f618** [fabe/gatsby-starter-deck#24]
Large images are overflowing or cropping in height. The ability to adjust max image sizes would be nice.

**Comment by antoinerousseau** [comment]
You can reduce `maxWidth` in `gatsby-config.js` as a temporary workaround, or tweak the stylesheet

**Comment by fabe** [comment]
I'm archiving this repository in favor of https://github.com/jxnblk/mdx-deck/tree/master/packages/gatsby-theme ✌️
