### ISSUE TITLE
Mdx ? 

### ISSUE THREAD

**Issue by PaulineStich** [fabe/gatsby-starter-deck#26]
It's using md, while it could be more interesting to build this with mdx.

**Comment by elihanover** [comment]
Do you know any slide decks with mdx?

**Comment by PaulineStich** [comment]
Nope. I used mdx without sliding decks instead. Would be very interesting to build one 👍

**Comment by fabe** [comment]
I'm archiving this repository in favor of https://github.com/jxnblk/mdx-deck/tree/master/packages/gatsby-theme ✌️
