### ISSUE TITLE
Retina images

### ISSUE THREAD

**Issue by antoinerousseau** [fabe/gatsby-starter-deck#27]
I had to add this option in the `gatsby-remark-images` `options` (`gatsby-config.js`):

```js
wrapperStyle: fluidResult => `width:${fluidResult.presentationWidth / 2}px;`,
```

In order for my images to be displayed at half their pixels size, so they don't appear blurry on HDPI screens.
But it's a hack and it could be improved.

**Comment by austriker27** [comment]
This is helpful, thanks!

**Comment by fabe** [comment]
I'm archiving this repository in favor of https://github.com/jxnblk/mdx-deck/tree/master/packages/gatsby-theme ✌️
