### ISSUE TITLE
Hot reloading doesn't seem to be working

### ISSUE THREAD

**Issue by damienstanton** [fabe/gatsby-starter-deck#6]
This is the environment where I have the issue
macOS: 10.13.6
Gatsby: 1.1.58
Node: 10.9.0
npm: 6.4.1

Currently, saving `src/slides.md` recompiles the Gatsby project without errors, but the rendered slides do not change. I have to stop and restart the `gatsby develop` server to actually see any changes.

I have tried this in an incognito session and with cache disabled, and still have the problem.

**Comment by fabe** [comment]
Thanks for opening this! Hot reloading wasn't implemented yet, but should be working now with #7.
